// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "gateway_app" => http://localhost:8080/admin/info/gateway_app
// "gateway_service_info" => http://localhost:8080/admin/info/gateway_service_info
//
// example end
//
var Generators = map[string]table.Generator{

	"gateway_app":          GetGatewayAppTable,
	"gateway_service_info": GetGatewayServiceInfoTable,

	// generators end
}
